[tool.poetry]
name = "reports"
version = "0.1.0"
description = "Project description"
authors = ["toptuk49"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
